### ISSUE TITLE
nvidia-docker: Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by tycho01** [tycho01/nix-config#101]
```
$ docker pull mapd/mapd-ce-cuda
$ docker run --runtime=nvidia -d --name mapd -p 9091-9092:9091-9092 -v /home/username/mapd-storage:/mapd-storage mapd/mapd-ce-cuda
Error response from daemon: Unknown runtime specified nvidia
```

**Comment by tycho01** [comment]
obviously that gives me [no hits](https://github.com/NixOS/nixpkgs/search?q=%22Unknown%20runtime%20specified%20nvidia%22)... I may wanna ask at https://github.com/NixOS/nixpkgs/pull/51733 or file an issue.

**Comment by tycho01** [comment]
I get this error also using the invocation `nvidia-docker run ...`.

**Comment by tycho01** [comment]
alternative repro for pytorch:
```
docker pull nvcr.io/nvidia/pytorch:19.03-py3
nvidia-docker run -ti --rm -v $PWD:/app nvcr.io/nvidia/pytorch:19.03-py3 python
```

**Comment by Yorwba** [comment]
Hi, I found this issue while searching for the exact same `Unknown runtime specified nvidia` error message. There's an option `virtualisation.docker.enableNvidia` that is required to register the nvidia runtime with the docker daemon.

Adding the code below to my `configuration.nix` solved the problem for me:
```
  hardware.opengl.driSupport32Bit = true; # Precondition for enableNvidia below
  virtualisation.docker = {
    enable = true;
    enableNvidia = true;
  };
```

**Comment by tycho01** [comment]
That's awesome, thank you! :grin:

**Comment by tscholak** [comment]
I just ran into this problem. Small world.
