### ISSUE TITLE
can't use extensions.gnome.org

### ISSUE THREAD

**Issue by KiaraGrouwstra** [tycho01/nix-config#8]
- https://github.com/NixOS/nixpkgs/issues/34184
- https://github.com/NixOS/nixpkgs/issues/30022
- https://github.com/NixOS/nixpkgs/issues/26981

**Comment by tycho01** [comment]
incidentally, I'm seeing `chrome-gnome-shell` as one of only few executables listed in the user path `~/.nix-profile/bin` instead of `/run/current-system/sw/bin`.
