### ISSUE TITLE
telegram issues

### ISSUE THREAD

**Issue by tycho01** [tycho01/nix-config#9]
- plaintext config: https://github.com/telegramdesktop/tdesktop/issues/4879
- use system fonts: https://github.com/telegramdesktop/tdesktop/issues/90
- CJK fonts: https://github.com/telegramdesktop/tdesktop/issues/3575

**Comment by tycho01** [comment]
closing as unactionable -- these issues are on their end, not my nix config.

**Comment by rafaelribeiroo** [comment]
@KiaraGrouwstra private folder where root is proprietary?

**Comment by KiaraGrouwstra** [comment]
@rafaelribeiroo I'll have to admit, given it's been some time I don't remember much about this issue 🥲
